config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'static_pages#home'
  get :about, to: 'static_pages#about'
  get :faq, to: 'static_pages#FAQ'



  # get '/cart' => 'cart#index'
  # get '/cart/clear' => 'cart#clearCart'
  # get '/cart/:id' => 'cart#add'

  get '/users/:id' => 'devise/dashboards#show'
  get :cart, to: "carts#show"
  post :add_item, to: "carts#add_item"
  delete :remove_item, to: "carts#remove_item"
  patch :update_item, to: "carts#update_item"

  resources :orders
  resources :ordered_items
  resources :items
  resources :categories
  resources :addresses
  resources :carriers

  get :checkout, to: "addresses#address"
  get :checkout2, to: "carriers#carrier"

  get :shippings, to: "shippings#index"
  get :order_confirmation, to: "shippings#order_confirmation"
  get :payments, to: "payments#index"


  scope '/webhooks', controller: :webhooks do
      post 'payment-callback', to: 'webhooks#payment_callback', as:
        :payment_callback
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/carrier.rb
class Carrier < ApplicationRecord
end

app/controllers/carriers_controller.rb
class CarriersController < ApplicationController

  def carrier
    @carriers =  Carrier.all
  end


  def index
    @carriers = Carrier.all
  end


  def new
    @carrier = Carrier.new
  end


  def create
    @carrier = Carrier.new(carrier_params)

    if @carrier.save
      redirect_to carriers_path
    else
      render new_carrier_path
    end
  end


  def edit
    @carrier = Carrier.find_by(id: params[:id])
  end


  def update
    @carrier = Carrier.find_by(id: params[:id])

    if @carrier.update(carrier_params)
      redirect_to carriers_path
    else
      redirect_to edit_carrier_path(@carrier)
    end
  end


  private

  def carrier_params
    params.require(:carrier).permit(:user_id, :name, :destination, :price)
  end


end

app/views/carriers/carrier.html.erb
<div class="container">
  <h1>Confirm Delivery Method</h1>

<%= form_tag order_confirmation_path, method: :get do %>
  <% @carriers.each do |carrier| %>
  <%= radio_button_tag 'carrier', carrier.id, true %>
  <%= label_tag "carrier_#{carrier.id}", "Carrier" %>
  <td><%= carrier.name %></td><br>
  <td><%= carrier.destination %></td><br>
  <td><%= carrier.price %></td><br>
  <br>
  <% end %>
  <a href="/checkout" class="btn waves-effect waves-light">Back</a>

<%= submit_tag 'Next', class:"btn waves-effect waves-light" %>
  <% end %>
  <br>

</div>

app/views/carriers/edit.html.erb
<div class="container">
  <%= form_for(@carrier) do |f| %>

    <h1>
      Edit Carrier
    </h1>

    <div>
      <h4> <%= f.label :text_field, "Name" %> </h4>
      <%= f.text_field :name %>
    </div>

    <div>
      <h4> <%= f.label :text_field, "Destination" %> </h4>
      <%= f.text_field :destination %>
    </div>

    <div>
      <h4> <%= f.label :text_field, "Price" %> </h4>
      <%= f.text_field :price %>
    </div>

    <div>
      <%= f.submit "Save Carrier", class:"btn waves-effect waves-light" %>
      <br><br>
    </div>
  <% end %>
</div>

app/views/carriers/index.html.erb
<div class="container">
<h1>Carriers</h1>

<%= link_to "Add New Carrier", new_carrier_path, class: "btn waves-effect waves-light" %>
<br><br>
<table>
  <thead>
    <th>Name</th>
    <th>Destination</th>
    <th>Price</th>
    <th></th>
  </thead>
  <tbody>
    <% @carriers.each do |carrier| %>

      <tr>
        <td><%= carrier.name %></td>
        <td><%= carrier.destination %></td>
        <td><%= number_to_currency(carrier.price, :unit => 'RM') %></td>
        <td><%= link_to "Edit Carrier", edit_carrier_path(carrier), class: "btn waves-effect waves-light" %>
</td>

      </tr>

    <% end %>
    </tbody>
</table>

</div>

app/views/carriers/new.html.erb
<div class="container">
  <%= form_for(@carrier) do |f| %>
    <h1>
      Add New Carrier
    </h1>

    <div>
      <h4> <%= f.label :text_field, "Name" %> </h4>
      <%= f.text_field :name %>
    </div>

    <div>
      <h4> <%= f.label :text_field, "Destination" %> </h4>
      <%= f.text_field :destination %>
    </div>

    <div>
      <h4> <%= f.label :text_field, "Price" %> </h4>
      <%= f.text_field :price %>
    </div>

    <div>
      <%= f.submit "Save Carrier", class:"btn waves-effect waves-light" %>
      <br><br>
    </div>
  <% end %>
</div>