config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'static_pages#home'
  get :about, to: 'static_pages#about'
  get :faq, to: 'static_pages#FAQ'



  # get '/cart' => 'cart#index'
  # get '/cart/clear' => 'cart#clearCart'
  # get '/cart/:id' => 'cart#add'

  get '/users/:id' => 'devise/dashboards#show'
  get :cart, to: "carts#show"
  post :add_item, to: "carts#add_item"
  delete :remove_item, to: "carts#remove_item"
  patch :update_item, to: "carts#update_item"

  resources :orders
  resources :ordered_items
  resources :items
  resources :categories
  resources :addresses
  resources :carriers

  get :checkout, to: "addresses#address"
  get :checkout2, to: "carriers#carrier"

  get :shippings, to: "shippings#index"
  get :order_confirmation, to: "shippings#order_confirmation"
  get :payments, to: "payments#index"


  scope '/webhooks', controller: :webhooks do
      post 'payment-callback', to: 'webhooks#payment_callback', as:
        :payment_callback
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/partials/_facebooksdk.html.erb
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1780174258920951',
      xfbml      : true,
      version    : 'v2.7'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

app/views/partials/_flash_messages.html.erb
<% flash.each do |k,v| %>
  <% k = "alert" if k == "danger" %>
  <% k = "success" if k == "notice" %>

  <%= javascript_tag do %>
    $toastClass = '<%= k %>';
    $toastContent = '<%= display_message(v) %>';
  <% end %>
<% end %>

app/views/partials/_footer.html.erb
<div class="footer">
  <footer class="page-footer indigo lighten-4">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="black-text">Old Folk Shop / <%=link_to "About", about_path %> / <%=link_to "FAQ", faq_path %></h5>
          <p class="black-text text-lighten-4">is pioneering e-commerce in Malaysia by offering a fast, secure and convenient online shopping experience with a broad product offering to meet elderlies' needs.</p>


        </div>
        <div class="col l3 s6">
          <h5 class="black-text">Categories</h5>
          <ul>
            <li><%=link_to "Medicines", category_path(1) %></li>
            <li><%=link_to "Adult Diapers", category_path(2) %></li>
            <li><%=link_to "Hearing Aids", category_path(3) %></li>
            <li><%=link_to "Elderly Phones", category_path(4) %></li>
          </ul>
        </div>
        <div class="col l3 s6">
          <h5 class="black-text">&nbsp;</h5>
          <ul>
            <li><%=link_to "Walkers", category_path(5) %></li>
            <li><%=link_to "Wheelchairs", category_path(6) %></li>
            <li><%=link_to "Bed Rails", category_path(7) %></li>
            <li><%=link_to "Bathroom Equipments", category_path(8) %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
        <div class="left">
          <span class="black-text text-lighten-3">Payment Methods:</span>
          <i class="fa fa-cc-visa fa-3x blue-grey-text" aria-hidden="true"> </i>
          <i class="fa fa-cc-mastercard fa-3x blue-grey-text" aria-hidden="true"> </i>
          <i class="fa fa-cc-amex fa-3x blue-grey-text" aria-hidden="true"> </i>
          <i class="fa fa-cc-paypal fa-3x blue-grey-text" aria-hidden="true"> </i>
        </div>
        <div class="right">
          <span class="black-text text-lighten-3">Follow Us:</span>
          <a href="#"><i class="fa fa-facebook-official fa-3x blue-grey-text" aria-hidden="true"> </i></a>
          <a href="#"><i class="fa fa-twitter-square fa-3x blue-grey-text" aria-hidden="true"> </i></a>
          <a href="#"><i class="fa fa-instagram fa-3x blue-grey-text" aria-hidden="true"> </i></a>
          <a href="#"><i class="fa fa-pinterest-square fa-3x blue-grey-text" aria-hidden="true"> </i></a>
        </div>
      </div>
    </div>
  </footer>
</div>

app/views/partials/_header.html.erb
  <nav class="indigo header" role="navigation">
    <div class="nav-wrapper container">
      <%=link_to "<i class='fa fa-envira' aria-hidden='true'></i> &nbsp;&nbsp; Old Folk Shop".html_safe, root_path, class:'brand-logo', id:'logo-container' %>
      <ul class="right hide-on-med-and-down">
        <li><%=link_to "Categories", categories_path %></li>
        <li><%=link_to "Items", items_path %></li>
        <li>
          <% if total_item() == 0 %>
          <%=link_to "<i class='fa fa-shopping-cart fa-2x' aria-hidden='true'></i>".html_safe, cart_path %>
          <% else %>
          <%=link_to "<i class='fa fa-shopping-cart fa-2x' aria-hidden='true'></i><span class='chip indigo lighten-2 white-text'>#{total_item()}</span>".html_safe, cart_path %>
          <% end %>
        </li>
        <% if user_signed_in? %>
        <li>
          <a href='#' class="dropdown-button" data-activates='dropdownUser'>
            <%=image_tag(current_user.image, height: '40', width: '40') unless current_user.image.blank?%>
            <% if current_user.name %>
            <%= current_user.name %>
            <% else %>
            Account
            <% end %>
            &nbsp;&nbsp;<i class="fa fa-chevron-circle-down" aria-hidden="true"></i>
          </a>
        </li>
        <!-- Dropdown Structure -->
        <ul id='dropdownUser' class='dropdown-content'>
          <li><%=link_to "Edit Password", edit_user_registration_path %></li>
          <li><%=link_to "Address Book", addresses_path %></li>

          <li><%=link_to "Orders", orders_path %></li>
          <% if current_user.admin? %>
          <li><%=link_to "Admin Panel", rails_admin_path %></li>
          <% end %>
          <li class="divider"></li>
          <li><%=link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        </ul>
        <% else %>
        <li><a class="modal-trigger" data-target="signup">Sign Up</a></li>
        <li><a class="modal-trigger" data-target="login">Log In</a></li>
        <% end %>
      </ul>


      <ul id="nav-mobile" class="side-nav">
        <li><%=link_to "Home", root_path %></li>
        <li><%=link_to "Categories", categories_path %></li>
        <li><%=link_to "Items", items_path %></li>
        <li><%=link_to "Shopping Cart".html_safe, cart_path %></li>
        <% if user_signed_in? %>
        <li><%=link_to "Account Settings", edit_user_registration_path %></li>
        <% if current_user.admin? %>
        <li><%=link_to "Admin Panel", rails_admin_path %></li>
        <% end %>
        <li class="divider"></li>
        <li><%=link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li class="divider"></li>
        <li><a class="modal-trigger" data-target="signup">Sign Up</a></li>
        <li><a class="modal-trigger" data-target="login">Log In</a></li>
        <% end %>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>

  </nav>

app/views/partials/_searchBar.html.erb
<section>
  <div class="container">
    <%= form_tag(items_path, method: "get", id: "search-form", class: "center-align center-block") do %>
    <%= search_field_tag :search, params[:search], placeholder: "Search for products, brands" %>
    <label for="search"><i class="fa fa-search fa-2x" aria-hidden="true"></i></label>
    <% end %>
  </div>
</section>