config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'static_pages#home'
  get :about, to: 'static_pages#about'
  get :faq, to: 'static_pages#FAQ'



  # get '/cart' => 'cart#index'
  # get '/cart/clear' => 'cart#clearCart'
  # get '/cart/:id' => 'cart#add'

  get '/users/:id' => 'devise/dashboards#show'
  get :cart, to: "carts#show"
  post :add_item, to: "carts#add_item"
  delete :remove_item, to: "carts#remove_item"
  patch :update_item, to: "carts#update_item"

  resources :orders
  resources :ordered_items
  resources :items
  resources :categories
  resources :addresses
  resources :carriers

  get :checkout, to: "addresses#address"
  get :checkout2, to: "carriers#carrier"

  get :shippings, to: "shippings#index"
  get :order_confirmation, to: "shippings#order_confirmation"
  get :payments, to: "payments#index"


  scope '/webhooks', controller: :webhooks do
      post 'payment-callback', to: 'webhooks#payment_callback', as:
        :payment_callback
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :load_cart
  after_action :write_cart, only: [:add_item, :remove_item, :update_item]

  def load_cart
    if cookies[:cart]
      @cart = JSON.parse(cookies[:cart])
    else
      @cart = {}
    end
  end

  def write_cart
    cookies[:cart] = JSON.generate(@cart)
  end

  def show
    @items = []
    @totalprice = 0

    @cart.each do |item_id,quantity|
      item = Item.find_by(id: item_id)
      item.define_singleton_method(:quantity) do
        quantity
      end
      @items << item

      @totalprice += item.price.to_f * item.quantity.to_i

    end
  end

  def add_item
    if @cart[params[:id]]
      quantity = params[:quantity].to_i
      quantityOld = @cart[params[:id]].to_i
      @cart[params[:id]] = quantityOld + quantity
      redirect_to cart_path
    else
      @cart[params[:id]] = params[:quantity]
      redirect_to cart_path
    end
    flash[:success] = "Item has been added to shopping cart."
  end

  def update_item
    if @cart[params[:id]]
      @cart[params[:id]] = params[:quantity]
    end
    redirect_to cart_path
  end

  def remove_item
    @cart.delete params[:id]
    flash[:success] = "Item has been removed from shopping cart."
    redirect_to cart_path
  end

end

app/views/carts/show.html.erb
<div class="container">

  <h1>Your Cart</h1>

  <% if @items.empty? %>
  Your Cart Is Currently Empty
  <br><br>
  <% else %>
  <% end %>

  <% if @items.empty? %>
  <% else %>
  <table class="striped">
    <thead>
      <tr>
        <th data-field="id">Item</th>
        <th data-field="name">Price</th>
        <th data-field="price">Qty</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
    <% @items.each do |item| %>
        <tr>
          <td><%= link_to item.name, item %></td>
          <td><%= number_to_currency(item.price, :unit => 'RM') %></td>
            <td>
            <%= form_tag update_item_path(id: item.id), method: :patch do%>
                <%= number_field_tag :quantity, item.quantity, id:"qty-cart" %>
              </td>
              <td>
                <%= button_tag 'Update', class:"btn waves-effect waves-light" %>
              </td>
              <td>
                <%= link_to "Delete", remove_item_path(id: item), method: :delete, class:"btn waves-effect waves-light" %>
              </td>
            <%end%>

        </tr>
    <% end %>
    </tbody>
  </table>
  <% end %>


    <% if @items.empty? %>
    <br>
    <%= link_to "Continue Shopping", items_path, class:"btn waves-effect waves-light" %>
    <br><br>
    <% else %>

    <h2>Order Total: <%= number_to_currency(@totalprice, :unit => 'RM') %></h2>
    <br>
    <%= link_to "Continue Shopping", items_path, class:"btn waves-effect waves-light" %>

    <a href="/checkout" class="btn waves-effect waves-light">Check Out Order</a>
      <br><br>
    <% end %>


  </ul>
</div>