config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'static_pages#home'
  get :about, to: 'static_pages#about'
  get :faq, to: 'static_pages#FAQ'



  # get '/cart' => 'cart#index'
  # get '/cart/clear' => 'cart#clearCart'
  # get '/cart/:id' => 'cart#add'

  get '/users/:id' => 'devise/dashboards#show'
  get :cart, to: "carts#show"
  post :add_item, to: "carts#add_item"
  delete :remove_item, to: "carts#remove_item"
  patch :update_item, to: "carts#update_item"

  resources :orders
  resources :ordered_items
  resources :items
  resources :categories
  resources :addresses
  resources :carriers

  get :checkout, to: "addresses#address"
  get :checkout2, to: "carriers#carrier"

  get :shippings, to: "shippings#index"
  get :order_confirmation, to: "shippings#order_confirmation"
  get :payments, to: "payments#index"


  scope '/webhooks', controller: :webhooks do
      post 'payment-callback', to: 'webhooks#payment_callback', as:
        :payment_callback
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  validates :name, presence: true,
                   length: { minimum: 4 }
  validates :description, presence: true,
                          length: { minimum: 10 }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all.order(created_at: :desc)
  end


  def show
    @category = Category.includes(:items).find(params[:id])
    @items = @category.items.order("created_at DESC").page params[:page]
  end


end

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= form_for(@category, url: category_path) do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="container">
  <h1>Categories</h1>
  <div class="row center-align">
    <% icons = ['wheelchair-alt', 'braille', 'wheelchair', 'blind', 'volume-control-phone', 'assistive-listening-systems', 'female', 'user-md'] %>
    <% @categories.each_with_index do |category, index| %>
    <div class="col s12 m4 l4">
      <h2 class="center blue-grey-text"><i class="fa fa-<%=icons[index]%>" aria-hidden="true"></i></h2>
      <h5 class="center"><%= link_to category.name, category_path(category) %></h5>
      <p class="light"><%= category.description %></p>
    </div>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<h1>Add New Category</h1>

<%= form_for(@category) do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div class="container">
  <h1>Items</h1>
  <div class="row center-align">
    <%= paginate @items %>
    <% @items.each do |item| %>
    <% next if item.status == 'inactive'%>
    <div class="col s12 m4 l4">
      <h2 class="center"><%= image_tag item.image, class: "responsive-img" %></h2>
      <h5 class="center"><%= link_to item.name, item_path(item) %></h5>
      <p class="light"><%= item.description %></p>
      <p class="light"><%= number_to_currency(item.price, unit: "RM ") %></p>
      <p class="light"><%= link_to "<i class='fa fa-shopping-cart fa-2x' aria-hidden='true'> </i> &nbsp; Add To Cart".html_safe, add_item_path(id: item, quantity: 1), method: :post, class: 'waves-effect waves-light btn' %></p>
    </div>
    <% end %>
    <%= paginate @items %>
  </div>
</div>